### PR TITLE
build: CI job for building different executables

### PR DESCRIPTION
**Pull request by fczuardi**

### CODE REVIEW

**Comment by sjcotto** [comment]
this is great!! - just one question, should we work on a settings page in order to the binaries make sense for a end user? at this moment a build already have the s3 configuration inside and that makes things easier to share it across coworkers, but in order to publish a public binary, maybe we should have a settings page to override that or what i your idea there?

**Comment by fczuardi** [comment]
> this is great!! - just one question, should we work on a settings page in order to the binaries make sense for a end user? at this moment a build already have the s3 configuration inside and that makes things easier to share it across coworkers, but in order to publish a public binary, maybe we should have a settings page to override that or what i your idea there?

oh, I didnt noticed that the binary included the credentials, so the values from env vars are not runtime, but build time instead?

**Comment by fczuardi** [comment]
If that is the case then distributing pre-built executables is not a good idea, and we should first make sure that the generated executables can be generic and not embed any configs

**Comment by sjcotto** [comment]
yes, exactly/

one idea is to add a settings option to set this values having the build, so anyone can download and configure, we can still have the option to build already with the credentials but for internal use and easy sharing. 

something like 

image

image

what do u think?

**Comment by fczuardi** [comment]
> yes, exactly/
> 
> one idea is to add a settings option to set this values having the build, so anyone can download and configure, we can still have the option to build already with the credentials but for internal use and easy sharing.
> 
> something like
> 
> image image
> what do u think?

I think that we can have one easier step before introducing more UI, we can use env var values as the default values at runtime. Do you know if built Electron apps can do that? (access env vars from the binary)

**Comment by fczuardi** [comment]
if reading the environment vars is not possible, we could maybe use arguments for those settings, then the person could launch with a `--env something` and not have to manually paste all values on a page

**Comment by sjcotto** [comment]
thanks a good idea, i belive that can work without code modification, let's test it. 

atm the build process in build.js takes the process.env if it's there 

```const { execSync } = require('child_process');

try {
    // Run the electron-builder command
    execSync('electron-builder', {
        stdio: 'inherit',
        env: {
            ...process.env,
            CSC_IDENTITY_AUTO_DISCOVERY: 'false' // Disable code signing for testing
        }
    });

    console.log('Build completed successfully.');
} catch (error) {
    console.error('Error during build process:', error);
}
```

if there is no .env file the build should work, and values can be passed with simple ARGS 

i did a quick test on mac, removed the .env file from my folder, created the build normally, then run the build with 

```
ACCESS_KEY=x ACCESS_SECRET=x ENDPOINT=x REGION=auto BUCKET_NAME=clipshare URL_PREFIX=https://clipshare.gopersonal.com/ ./clipshare.app/Contents/MacOS/clipshare
```

and it worked perfectly

**Comment by sjcotto** [comment]
so let's continue with this PR and binary thing :)

**Comment by fczuardi** [comment]
cool! nice to know, I started using an existing action but  still need to figure out how to include the `dist` files in the release, maybe following the docs of electron builder directly is easier, I will post progress here

**Comment by fczuardi** [comment]
hmm, I think it needs to have the version on the package.json to update to work, not sure, after some tweaking the assets are here on my fork: ~~https://github.com/fczuardi/clipshare/releases/tag/untagged-d79a4c34f58f090eeaa3~~

**Comment by sjcotto** [comment]
sounds good, that link is not working for me (404)

**Comment by fczuardi** [comment]
the link was for a draft release, try this: https://github.com/fczuardi/clipshare/releases/tag/v1.0.1

**Comment by sjcotto** [comment]
amazing!!

for mac, i belive we should change a little, instead of assuming ARM we can build with universal, like

```
- name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          args: "--mac --x64 --arm64 --universal --publish always"
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
```

i belive doing that will work on intel and ARM

**Comment by fczuardi** [comment]
Can you test this assets and see if the universal works? https://github.com/fczuardi/clipshare/releases/tag/v1.0.1-beta.7

**Comment by sjcotto** [comment]
that worked perfectly! 👏 👏

**Comment by fczuardi** [comment]
@sjcotto ok,I have removed the `--publish` and left it with the default automatic rules described on https://www.electron.build/configuration/publish.html

So either if there is a  draft release with a tag `v...` that matches the version on package.json, or if a tag `v...` is pushed, the assets will be uploaded to a github draft release on the releases page.

The actual publishing of a release will still be dependent on you, as the owner of the project, to click the Publish button :)

**Comment by fczuardi** [comment]
I tested the linux version from my fork here:

https://github.com/fczuardi/clipshare/releases/tag/v1.0.0

using:

`env $(cat .env | xargs) ~/Downloads/clipshare-1.0.0.AppImage`

And it worked as expected. Once the first release is out we may update the README with this tip to use the same .env file to set all variables before the command.

**Comment by sjcotto** [comment]
amazing work!

**Comment by sjcotto** [comment]
do u want to generate the first version?

**Comment by sjcotto** [comment]
created the version!

**Pull request merged**
